### ISSUE TITLE
Lineage proposal A.D.1.4X - A.D.1 descendant with 8 amino acid subs, 7 countries, 69 sequences

### ISSUE THREAD

**Issue by alanrice** [rsv-lineages/lineage-designation-A#2] opened 2024-06-28 15:17 UTC
Sequences: 69

IDs ([Virus name list](https://raw.githubusercontent.com/alanrice/RSV_lineage_proposal/main/A.D.1.4X/virusNameList.txt)): EPI_ISL_19116647, EPI_ISL_19001955, EPI_ISL_19001958, EPI_ISL_19001952, EPI_ISL_19001961, EPI_ISL_19160818, EPI_ISL_19160817, EPI_ISL_19160811, EPI_ISL_19160800, EPI_ISL_19160761, EPI_ISL_19160805, EPI_ISL_19160788, EPI_ISL_19160807, EPI_ISL_19160769, EPI_ISL_19160763, EPI_ISL_19160786, EPI_ISL_19160799, EPI_ISL_19160814, EPI_ISL_19160801, EPI_ISL_19160802, EPI_ISL_19160813, EPI_ISL_19160812, EPI_ISL_19160776, EPI_ISL_19160768, EPI_ISL_19160783, EPI_ISL_19160778, EPI_ISL_19160760, EPI_ISL_18698696, EPI_ISL_19160794, EPI_ISL_18622399, EPI_ISL_18968236, EPI_ISL_18507295, EPI_ISL_18507287, EPI_ISL_18507296, EPI_ISL_18507294, EPI_ISL_18939369, EPI_ISL_18622388, EPI_ISL_18999157, EPI_ISL_19174251, EPI_ISL_19174232, EPI_ISL_19174375, EPI_ISL_19174276, EPI_ISL_17950144, EPI_ISL_17808741, EPI_ISL_19069876, EPI_ISL_19069891, EPI_ISL_19131588, EPI_ISL_19131567, EPI_ISL_19131557, EPI_ISL_19131562, EPI_ISL_18682198, EPI_ISL_16132376, EPI_ISL_19131610, EPI_ISL_18985844, EPI_ISL_18829020, EPI_ISL_19015733, EPI_ISL_19015729, EPI_ISL_18653541, EPI_ISL_19005689, EPI_ISL_19015782, EPI_ISL_19015738, EPI_ISL_19015719, EPI_ISL_19028667, EPI_ISL_19015673, EPI_ISL_19005675, EPI_ISL_19140036, EPI_ISL_18810672, EPI_ISL_18999153, EPI_ISL_18999152

Countries/regions: Ireland (23), Spain (16), Australia (13), USA (9), Brazil (5), Canary Islands (2), Italy (1)

First collected on 2020-12-10 in South America / Brazil / Rio de Janeiro / Rio de Janeiro

Amino acid substitutions (with amino acid numbering relative to hRSV/A/England/397/2017|EPI_ISL_412866):
* F: L3S
* G: A122V, I133V, Y273H
* L: D146G, I1656T, G1735D, V1934I

[Nextclade tree zoomed to A.D.1 lineage](https://nextstrain.org/fetch/raw.githubusercontent.com/alanrice/RSV_lineage_proposal/main/A.D.1.4X/nextclade.auspice.json?f_Node%20type=New&label=clade:A.D.1) / 
[Full Nextclade tree](https://nextstrain.org/fetch/raw.githubusercontent.com/alanrice/RSV_lineage_proposal/main/A.D.1.4X/nextclade.auspice.json?f_Node%20type=New)
![Nextclade tree zoomed](https://raw.githubusercontent.com/alanrice/RSV_lineage_proposal/main/A.D.1.4X/zoomTreeNextclade.png)

[IQTree tree](https://raw.githubusercontent.com/alanrice/RSV_lineage_proposal/main/A.D.1.4X/A.D.1.4X.treefile) / [View in Taxonium](https://taxonium.org/?treeUrl=https%3A%2F%2Fproxy.taxonium.org%2Fproxy%3Furl%3Dhttps%253A%252F%252Fraw.githubusercontent.com%252Falanrice%252FRSV_lineage_proposal%252Fmain%252FA.D.1.4X%252FA.D.1.4X.treefile&ladderizeTree=true&treeType=nwk&xType=x_dist). Numbers in parentheses are SH-aLRT support (%) / ultrafast bootstrap support (%)

**Comment by goyastephanie** [comment] 2024-07-02 20:45
@alanrice thank you! We have confirmed the lineage and are working on updating the reference alignment to include the A.D.1.4 lineage.

FYI: I have detected the following amino acids in addition to the ones you shared: G_G225V, G_I133V, G_L314P, G_N103T, G_P298S, G_S144I, G_S270P

Cheers!

**Comment by AngieHinrichs** [comment] 2024-07-23 19:44
Closing this issue because #3 has been merged.  Thanks again @alanrice.

**Closed as completed by AngieHinrichs** 2024-07-23 19:44 UTC
